import ClientLayout from "./clientLayout";
import "./globals.css";


export const metadata = {
  title: "Audio-sharing-platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased `}
      >
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
