
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";
import { Providers } from "@/store/providers";
import AudioPlayer from "@/components/body/favorite/audio/AudioPlayer";

// Poppins font setup
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins", // Custom CSS variable for font
});

export const metadata = {
  title: "Audio-sharing-platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased container max-w-[2560px] mx-auto`}
      >
        <Providers>
          <Navbar />
          <div className="">{children}</div>

          

        </Providers>
      </body>
    </html>
  );
}
